#!/usr/bin/env ruby

site 'http://community.opscode.com/api/v1'

cookbook 'meta',
  :path => 'site-cookbooks/meta'

cookbook 'sprout-osx-rbenv',
  :github => 'pivotal-sprout/sprout',
  :path => 'sprout-osx-rbenv'

cookbook 'sprout-osx-git',
  :github => 'pivotal-sprout/sprout',
  :path => 'sprout-osx-git'

cookbook 'sprout-osx-base',
  :github => 'pivotal-sprout/sprout',
  :path => 'sprout-osx-base'

cookbook 'pivotal_workstation',
  :github => 'pivotal-sprout/sprout',
  :path => 'pivotal_workstation'

cookbook 'sprout-osx-apps',
  :github => 'pivotal-sprout/sprout',
  :path => 'sprout-osx-apps'

cookbook 'sprout-osx-settings',
  :github => 'pivotal-sprout/sprout',
  :path => 'sprout-osx-settings'

cookbook 'sprout-pivotal',
  :github => 'pivotal-sprout/sprout',
  :path => 'sprout-pivotal'

cookbook 'osx',
  :github => 'pivotal-sprout/sprout',
  :path => 'osx'

cookbook 'sprout-osx-rubymine',
  :github => 'pivotal-sprout/sprout-osx-rubymine'

cookbook 'sprout-homebrew',
  :github => 'pivotal-sprout/sprout-homebrew'

cookbook 'sprout-terminal',
  :github => 'pivotal-sprout/sprout-terminal'

cookbook 'sprout-postgresql',
  :github => 'pivotal-sprout/sprout-postgresql'
