#!/usr/bin/env ruby

site 'https://supermarket.getchef.com/api/v1'

cookbook 'sprout-rbenv',
  :github => 'pivotal-sprout/sprout-rbenv'

cookbook 'sprout-ruby',
  :github => 'pivotal-sprout/sprout-ruby'

cookbook 'sprout-mysql',
  :github => 'pivotal-sprout/sprout-mysql'

cookbook 'sprout-git',
  :github => 'pivotal-sprout/sprout-git'

cookbook 'sprout-base',
  :github => 'pivotal-sprout/sprout-base'
#  :git => '/Users/jcuzella/src/pub/cookbooks/sprout-base',
#  :ref => 'develop'

cookbook 'sprout-osx-apps',
  :github => 'pivotal-sprout/sprout-osx-apps'

cookbook 'sprout-osx-settings',
  :github => 'pivotal-sprout/sprout-osx-settings'

cookbook 'osx',
  :github => 'pivotal-sprout/osx'

cookbook 'sprout-terminal',
  :github => 'pivotal-sprout/sprout-terminal'

cookbook 'sprout-postgresql',
  :github => 'pivotal-sprout/sprout-postgresql'

cookbook 'sprout-ssh',
  :github => 'pivotal-sprout/sprout-ssh'

cookbook 'plist',
 :github => 'carsomyr/chef-plist',
 :ref => 'master',
 :path => 'vendor/cookbooks/plist'

cookbook 'lyraphase_workstation', '~> 2.0',
 :github => 'trinitronx/lyraphase_workstation'
# :ref => 'develop'
# :git => '/Users/jcuzella/src/pub/cookbooks/lyraphase_workstation',
# :ref => 'develop'

## Broken dependency on sprout-homebrew
## Deprecated by sprout-jetbrains-editors::rubymine 
# cookbook 'sprout-rubymine',
#   :github => 'trinitronx/sprout-rubymine'

cookbook 'homebrew',
    '>= 1.13.0'
#  :github => 'kbruner/homebrew',
#  :ref => 'issue71'

cookbook 'sprout-jetbrains-editors',
  :github => 'pivotal-sprout/sprout-jetbrains-editors'

# mingw 1.0 and build-essential 4.0 add a dependency to compat_resource,
# which does not load correctly with Rubygems 2.0.14, the Rubygems version
# bundled with OS X 10.11.4.
cookbook 'mingw', '= 0.1.1'
cookbook 'build-essential', '= 3.2.0'
