#!/usr/bin/env bash

function clear_chruby() {
  if [ -f /usr/local/share/chruby/chruby.sh ]; then
    # shellcheck disable=SC1091
    source /usr/local/share/chruby/chruby.sh
    chruby system
  fi
}

function use_local_gems() {
  export GEM_HOME=tmp/ruby/2.0.0
  export GEM_PATH=tmp/ruby/2.0.0
  export PATH=${GEM_HOME}/bin:${PATH}
}

function get_dependencies() {
  gem install bundler --no-document
  bundle install
}

function main() {
  clear_chruby
  use_local_gems
  get_dependencies

  bundle exec soloist
}

main
