include_recipe "sprout-osx-apps::iterm2"
include_recipe "sprout-osx-base::homebrew"
include_recipe "sprout-osx-apps::virtualbox"
include_recipe "custom::btsync"

include_recipe "pivotal_workstation::git_config_global_defaults"
include_recipe "pivotal_workstation::git_scripts"
include_recipe "sprout-osx-settings::global_environment_variables"
include_recipe "pivotal_workstation::unix_essentials"
include_recipe "pivotal_workstation::vim"
include_recipe "pivotal_workstation::vim_config"
