name             'custom'
maintainer       'FlatStack'
maintainer_email 'fs-admin@flatstack.com'
license          'MIT'
description      'Various apps'
version          '0.1.0'
supports         'mac_os_x'
depends          'dmg'
