name                  'meta'
maintainer           'Pivotal Labs'
maintainer_email  'sprout-maintainers@pivotallabs.com'
license                 'MIT'
description           'Uses pivotal_workstation to configure an OSX workstation for ruby development'
long_description    'Uses pivotal_workstation to configure an OSX workstation for ruby development'
version                 '0.1.1'
supports               'mac_os_x'
depends               'sprout-pivotal'
