maintainer        'Pivotal Labs'
maintainer_email  'accounts@pivotallabs.com'
license           'MIT'
description       'Uses pivotal_workstation to configure an OSX workstation for ruby development'
long_description  'Uses pivotal_workstation to configure an OSX workstation for ruby development'
version           '0.1.1'
supports          'mac_os_x'

depends           'pivotal_workstation'
depends           'sprout-osx-settings'
depends           'sprout-osx-apps'
depends           'sprout-pivotal'
