maintainer        'FlatStack'
maintainer_email  'fs-admin@flatstack.com'
license           'MIT'
description       'Uses sprout to configure an OSX workstation for ruby development'
long_description  'Uses sprout to configure an OSX workstation for ruby development'
version           '0.1.0'
supports          'mac_os_x'

depends           'pivotal_workstation'
depends           'sprout-osx-settings'
depends           'sprout-osx-apps'
